US474035 Rest Adapter implementation
FileAnalysisSuite/adapter-rest pull request #1
Opened 2022-07-27 09:22 UTC by kploch

2022-07-27 09:25 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](http://sou-jenkins2.swinfra.net:8080/job/Create-New-Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=FileAnalysisSuite&REPO_NAME=adapter-rest&BRANCH_NAME=US474035RestInitial) to go ahead and create the build...

2022-07-27 09:31 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
http://sou-jenkins2.swinfra.net:8080/job/FileAnalysisSuite/job/FileAnalysisSuite~adapter-rest~US474035RestInitial~CI

2022-08-08 15:18 UTC, dermot-hardy commented
Was the review request intentionally revoked?  The conflicts need to be resolved first anyway.

2022-08-10 15:25 UTC, dermot-hardy requested changes
Merge main branch in and resolve conflicts.

2022-09-07 02:19 UTC, dermot-hardy approved these changes

2022-09-07 02:19 UTC, dermot-hardy commented on .editorconfig
> +end_of_line = crlf
Great idea having this file, but can we make LF and UTF-8 without the BOM the standard?

Currently the [.gitattributes](https://github.com/FileAnalysisSuite/adapter-rest/blob/b2f613b388ffc23ebd00819b9d81949f2896b463/.gitattributes) file results in all files being automatically converted from CRLF to LF when they are committed.

2022-09-07 02:19 UTC, dermot-hardy commented on RestAdapter.sln
> +		Directory.Build.props = Directory.Build.props
Did you mean to put `Directory.Build.props` in the `sepg` solution folder?

2022-09-07 02:19 UTC, dermot-hardy commented on src/MicroFocus.FAS.Adapters.Rest/app.manifest
> -        <requestedExecutionLevel level="requireAdministrator" uiAccess="false" />
I thought adapters had to run as administrator?  Is that not right?

2022-09-07 02:19 UTC, dermot-hardy commented on tests/MicroFocus.FAS.Adapters.Rest.Tests/StreamExtensions.cs
> +
Unnecessary using directive

2022-09-07 02:19 UTC, dermot-hardy commented on tests/MicroFocus.FAS.Adapters.Rest.Tests/RestAdapterTests.cs
> +                                                                                                                                                                       i.Metadata.Version == item.Metad
There has to be a better way to indent this.  It's massively over the right-hand side guideline.

2022-09-07 02:19 UTC, dermot-hardy commented on tests/MicroFocus.FAS.Adapters.Rest.Tests/RestAdapterTests.cs
> +        public void CreateDescriptor_should_call_api_to_obtain_descriptor([Frozen] Mock<IAdapterApi> adapterApi,
I'm probably not the best person to review this, since I've never heard of `[Theory]`, `[AutoMockData]`, or `[Frozen]` before.

2022-09-07 02:19 UTC, dermot-hardy commented on src/MicroFocus.FAS.Adapters.Rest/ProxyDetails.cs
> +    public class ProxyDetails
We have to supply our own proxy configuration?  I'm not saying this is wrong but I half expected .net to have a standard for this.

2022-09-20 22:31 UTC, kploch commented on src/MicroFocus.FAS.Adapters.Rest/app.manifest
> -        <requestedExecutionLevel level="requireAdministrator" uiAccess="false" />
Nope

2022-09-20 22:41 UTC, kploch commented on src/MicroFocus.FAS.Adapters.Rest/ProxyDetails.cs
> +    public class ProxyDetails
Well, there's `WebProxy` class in .NET is not a POCO and not suitable for the configuration file.

2022-09-20 22:43 UTC, kploch commented on RestAdapter.sln
> +		Directory.Build.props = Directory.Build.props
Yup

2022-09-20 22:43 UTC, kploch commented on tests/MicroFocus.FAS.Adapters.Rest.Tests/RestAdapterTests.cs
> +                                                                                                                                                                       i.Metadata.Version == item.Metad
Improved, but it'll get reformatted automatically. And it's just tests.

2022-09-20 23:00 UTC, merged